---
- name: Run updates on all guests except Semaphore host
  hosts: 'guests:!lxc-109'
  gather_facts: true
  any_errors_fatal: true
  become: true
  tasks:
    - name: Include common guest update tasks
      ansible.builtin.include_tasks: 'tasks/update-guests-common.yml'

- name: Run updates on Semaphore host
  hosts: lxc-109
  gather_facts: true
  become: true
  tasks:
    - name: Include common guest update tasks
      ansible.builtin.include_tasks: 'tasks/update-guests-common.yml'
